### ISSUE TITLE
Testnet not passing Step 2 (Creation), nor even logging in at all (wss failure of JS)

### ISSUE THREAD

**Issue by simcity4242** [greenaddress/WalletCrx#11]
This has been an issue for >6 months. I have emailed about it several times. Chrome, Firefox (Windows7 and Ubuntu 14.04 versions, respectively), Chrome/Safari/Lastpass browser on iOS 8 iPad, Chrome/Firefox/Browser on Android Kit Kat for a Galaxy S4 GT-i9505: all of those fail will pass Step 2 of creating a new testnet wallet, nor will logging in pass the same authentication stage. I'm not great with JavaScript debugging, but payload data seems to be the main error showing (cannot connect to server, looking for this file: 
![capture](https://cloud.githubusercontent.com/assets/4364971/6243437/50906f90-b795-11e4-9902-83acbb85a43b.jpg)
. I have cleared the cache of saved files each time. 
![capture](https://cloud.githubusercontent.com/assets/4364971/6243423/d4bdc674-b794-11e4-9a94-19c9585db20c.GIF)

**Comment by greenaddress** [comment]
We have release on the Chrome Store a testnet wallet  https://chrome.google.com/webstore/detail/greenaddress-testnet/kbdjlmbommjjeojcngejkamofpnjhahl (and test.greenaddress.it works on chrome/firefox on osx/windows/linux)
