### ISSUE TITLE
delete address book entries?

### ISSUE THREAD

**Issue by JPUnix** [greenaddress/WalletCrx#24]
I would like to know if there is a way to delete address book entries? If there is not a way can it be added?

**Comment by greenaddress** [comment]
Hello,

In the address book on the right hand side of each entry there is a little bin icon that allows to delete address book entries one by one(should require non watch only).

**Comment by JPUnix** [comment]
Hmm... It's not there for me. I'm using 0.0.91 on Windows 7 using a Ledger HW.1 as the wallet source.

![address](https://cloud.githubusercontent.com/assets/7219701/19837741/0e6fd52e-9e8e-11e6-88b4-e9f3b096376a.jpg)

**Comment by greenaddress** [comment]
@JPUnix thats for the bug report, this has been fixed in https://github.com/greenaddress/GreenAddressWebFiles/commit/13bec469ea566a6e0d702cbd6757173ef15908af - the fix will be part of the next release.

**Comment by JPUnix** [comment]
Thanks! I'll close the ticket now.

**Comment by greenaddress** [comment]
Hello, the fix has been released (version 0.0.92)
