### ISSUE TITLE
[Solved]:Could not login with Nano S  the message could be improved.

### ISSUE THREAD

**Issue by gabridome** [greenaddress/WalletCrx#25]
Ledger nano S is detected and the message correctly inform to "open the bitcoin app" but I understood I had to open Greenaddres (that of course was already there). I spent a lot of time before realizing I had to enter INTO the bitcoin app INTO the device. To see "Bitcoin" in the small screen is not enough.

The message is somehow misleading because I had the Greenaddress app open and for me THAT was the bitcoin app. a "open the bitcoin app on the device" maybe could help a little more.

Also it is very hard to copy the error messages because the disappear quickly and sometimes they hide under other windows.

**Comment by greenaddress** [comment]
thanks for the feedback - for the time being i've added "on the device" as you suggested as a fix https://github.com/greenaddress/GreenAddressWebFiles/commit/d66dd27ca098ac41c5f075a7eebf44a82a046534 but indeed it would be better to have notifications appear in a better way or maybe be sticky so i'll keep this issue open to keep track of notifications improvements
