### ISSUE TITLE
http://s7a4rvc6425y72d2.onion/ doesn't work

### ISSUE THREAD

**Issue by RyanSinger** [greenaddress/WalletCrx#26]
When I go into http://s7a4rvc6425y72d2.onion/ I get:

![image](https://cloud.githubusercontent.com/assets/2665386/20908707/8756d3f4-bb0b-11e6-9082-d99bb74db336.png)

**Comment by greenaddress** [comment]
Thanks for the report!

Is it possible you have javascript disabled? GA web doesn't work without.  

I see the noscript icon and perhaps that's the reason.


 In the future I think we want to provide some full apps for desktop that supports Onion as our Chrome app only supports Tor via https not with Onion addresses and our web will be deprecated (and in general will be often blocked by things like no script)

We run some tests and for us the onion address works with tbb 6.0.7 and security level low (the default) and in GreenBits in Tor mode with Orbot.
