### ISSUE TITLE
2FA issue

### ISSUE THREAD

**Issue by Artifix1985** [greenaddress/WalletCrx#27]
Hello! I've been using greenaddress (chrome exp.) walley for a while, but unfortunately ~2 weeks ago something went wrong: my 2FA broke down. I am not receiving sms at all. The problem is that i don't have another 2FA option or even nLocktime, so the only option for me is SMS 2FA which doesn't work correctly. 
I am also a bit confused 'cause support doesn't answer my emails for weeks so the last hope for me is to leave ticket here and to hope against hope. It's not even fair, since this issue is based on the fault of the service.

**Comment by pvdyck** [comment]
You may have accidentally discovered their business model ;-)

**Comment by greenaddress** [comment]
Do you still have SMS problems? if so please email us with your phone number and we'll manually process it.

Thanks

**Comment by pvdyck** [comment]
@greenaddress =>yes I still have the problem ! what is your email so I can send my phone number ?
Thanks !

**Comment by pvdyck** [comment]
(I still have the password for the wallet of course)
