### ISSUE TITLE
Two factor authentication by mail doesn't works

### ISSUE THREAD

**Issue by fbattistin** [greenaddress/WalletCrx#31]
Hello,
In my greenaddress account I configured the two factor authentication by mail, but when I try to send a payment, the mail with security code doesn't works, so I'm unable to unblock the bitcoin in my wallet.
I tried to disable the two factor authentication, but I'm unable because for disable it is requested... the mail code; so I'm in a loop.

Can you disable my two factor authentication or check the mail problem?

I tried to sen a mail to info@greenaddress.it but don't receive any answer.

Thank you for the support.

Francesco

**Comment by greenaddress** [comment]
Should be fixed now. please reopen if you have issues.
