### ISSUE TITLE
2FA issue no sms

### ISSUE THREAD

**Issue by JRcoder3** [greenaddress/WalletCrx#32]
Hello! 
same problem as another issue:
I've been using greenaddress (chrome exp.) wallet for a while, and I never recieve a request for 2FA authentication SMS. And the phone number was not asked during account creation.
But now a 2FA is asked when I try to send BTC.
The problem is that I don't have another 2FA option or even nLocktime, so the only option for me is SMS 2FA which doesn't work.

Please help regarding this issue

**Comment by greenaddress** [comment]
If the phone number was never asked it means you never setup SMS - the only way to have two factor authentication enabled is to pass a mobile number and inputting a code sent to the number for verification.

We can't reveal the number for privacy reasons and you shouldn't put personal details on github so I suggest you remove them

Did you put the mnemonic in a place where someone else could have added the SMS two factor? or perhaps you added it and changed number? Or used a different number?

Regards

**Comment by JRcoder3** [comment]
Thanks for reply, I'll remove my personal details on GitHub

I always had the same phone number but I am 90% sure of never encoded it in
the system.
And nobody has access to my mnemonic.
I am very confused because I can't do nothing with my account now, that's
terrible.
What can I do?

Please help me
Regards



2017-03-14 16:47 GMT+01:00 GreenAddress <notifications@github.com>:

**Comment by greenaddress** [comment]
We'll get back to you by email for a solution.

Please meanwhile do not make any more SMS 2FA request if you don't want it to be locked for 24 hours or even a week.

Thanks

**Comment by JRcoder3** [comment]
Ok, thank you 
I'll don't make other request here.

Regards
