### ISSUE TITLE
Trezor and BitID support ?

### ISSUE THREAD

**Issue by aussiehash** [greenaddress/WalletCrx#5]
At this stage it would appear that Chrome has broken all support for Trezor's plugin and this will not be restored until Trezor Bridge is released

Using Safari and greenaddress.it, Trezor is detected, but only becomes configurable after the wallet/mnemonic/2fa has been created, under SETTINGS > write to hardware wallet.
This announces on Trezor "Do you really want to wipe the device? All data will be lost. Cancel/Confirm.

Safari/greenaddress.it never shows the "write to hardware wallet" icon in the RLQ of the Step 1 mnemonic as shown here
http://postimg.org/image/3mb2eam07/ 
(From https://bitcointalk.org/index.php?topic=787418)

On the other hand Creating a Chrome CRX extension does show the green icon at Step 1 : mnemonic, but clicking on it gets stuck at "Please connect/reconnect your wallet USB device to Proceed."
Presumably because the Chrome has broken the Trezor plugin support.

`Does WalletCrx running as a Chrome extension currently  support Trezor (apart from the broken plugin) ?`

`Does greenaddress.it currently support Trezor when running in Safari with Trezor plugin enabled ?`

`Does greenaddress.it or WalletCrx support BitID login, either for Trezor or btchip ?`

**Comment by lichtamberg** [comment]
Trezor supports now Multisig with their newest version. Any eta when the trezor/greenaddress multisig combination will work? Im quite excited! :D

**Comment by greenaddress** [comment]
@lichtamberg GreenAddress supports Trezor in WalletCrx and GreenBits since Trezor supports multisig. We do not still support BitId so we can leave this issue open or open a new one for BitId
